### ISSUE TITLE
Trying to get all Pset properties

### ISSUE THREAD

**Issue by IFChaos** [xBimTeam/XbimPropertySets#1]
Hello

I'm here again, this time i would like to know what is the correct method to obtain all properties of an object, including properties by type and specific properties of the object.

At the moment i'm using this code:

        if (SelectedText == "IFCCOLUMN")
        {
            var TotalColumns = XBModel.Instances.OfType<Xbim.Ifc2x3.SharedBldgElements.IfcColumn>();
            Xbim.Ifc2x3.SharedBldgElements.IfcColumn col = TotalColumns.ElementAt(listBox1.SelectedIndex);
            textBox1.Text = "";
            var ifcObj = col as Xbim.Ifc2x3.Kernel.IfcObject;
            var ifcType = Xbim.IO.IfcMetaData.IfcType(ifcObj);

             Dictionary<IfcLabel, Dictionary<IfcIdentifier, IfcValue>> result = col.GetAllPropertySingleValues();

             for (int i = 0; i < result.Count; i++)
             {
                 var Meta = result.ElementAt(i).Value;
                 for (int j = 0; j < Meta.Count; j++)
                 {
                     var SubMeta = Meta.ElementAt(j);
                     textBox1.Text += "\t" + SubMeta.Key + ": " + SubMeta.ToString() + Environment.NewLine;
                 }
             }
        }

But i'm sure this is not the best way to do it.

Thank you in advance.

**Comment by martin1cerny** [comment]
Hi @IFChaos,

I'm sorry but I'm not sure what you are trying to achieve. Do you need all properties existing in the specific model or set of properties which are predefined in the IFC2x3 schema for a specific type? These are two very different things.

 Also, may I ask you to clear the code before posting next time? I will save my/our time when reading through unrelated content.

Thanks 

Martin

**Comment by IFChaos** [comment]
Hi Martin

I would like to edit the predefined properties of a IFC2X3 type. So the process should be to list all the types present in the model and then choose a type and edit the predefined properties of this type.

But in the IFC files it is also possible to generate specific customized properties for a type or an object, so i also want to edit these specific customized properties.

And later i would like to edit general model properties like unity values, conversion values, etc.

This is the last serious problem i'm facing with xbim, if i solve it i think i will be able to advance in an autonomous way.

Thanks in advance and sorry for these intensive journeys. Next week i need to show a presentation of a CAD prototype able to work directly with IFC files, and i want to use Xbim. So i need to show the general lines of the project.

Thanks in advance.

**Comment by martin1cerny** [comment]
I'm still not sure if I understand your needs but this might help you:

* XbimModel represents all data in IFC file and you can use it to obtain/edit anything in the model including object properties
* type is ambiguous in terms of IFC. Do you mean type as an information object type (like IfcWall), or as an IFC object type (IfcWallType)? Properties assigned to IfcWallType are also valid for all instances of IfcWall if the relationship is defined between the instance of IfcWall and instance of IfcWallType.
* To get an instance of IfcTypeObject assigned to IfcObject you can use extension function *IfcObject.GetDefiningType()* 
* if you only want to get simplified structure of properties and property sets contained in your IFC file you can use extension function *IfcObject..GetAllPropertySingleValues()*. You won't be able to change values this way but it is simpler that to get all **single value** properties
*to get all properties and property sets you will need to traverse relations with something like this (not tested):
 
```c#
    IEnumerable<IfcRelDefinesByProperties> relations = obj.IsDefinedByProperties.OfType<IfcRelDefinesByProperties>();
    foreach (IfcRelDefinesByProperties rel in relations)
    {
        IfcPropertySet pSet = rel.RelatingPropertyDefinition as IfcPropertySet;
        if (pSet == null) continue;
        foreach (IfcProperty prop in pSet.HasProperties)
        {
            IfcPropertySingleValue singleVal = prop as IfcPropertySingleValue;
            if (singleVal == null) continue;
        }
    }
```

* if you want to find out which properties are recommended by buildingSMART for different object types you can find all these in this project (XbimPropertySets) with something like this (not tested):
```c#
    var mgr = new Definitions<PropertySetDef>(Version.IFC2x3);
	mgr.LoadAllDefault();
	var typeName = "IfcWall";
	var wallPredefPropSets = mgr.DefinitionSets.Where(p => p.ApplicableClasses.Any(c => c.ClassName == typeName));
	foreach(var pSet in wallPredefPropSets)
	{
		foreach(var propDef in wallPredefPropSets.PropertyDefinitions)
		{
			//do something with the definitions
		}
	}
 ```
Bare in mind that these definitions are just a meta description of the property sent and you will have to convert them into eventual instances in the model yourself. Also this code won't give you all the properties defined on the level of IfcObject, IfcElement ang IfcBuildingElement. You have to traverse type hierarchy if you want to get all of them.

**Comment by IFChaos** [comment]
I'm interested in both, the properties of IFCWALL, IFCWINDOW, IFCSLAB, etc... and also the properties of IFCWALLTYPE, IFCWINDOWTYPE,  IFCSLABTYPE, etc... 

For example i select a wall, immediately the properties of this object IFCWALL shows up. But i also want to be able to modify the properties of the IFCWALLTYPE that is assigned to this wall. This is the basic idea.

Another question is, what if i had created a special Property set for an object IFCWALL or an IFCWALLTYPE? I can do it using Xbim?

Just imagine i need to insert a special property, that is not present in the predefined Psets, to an IFCWALL and later i need to inset aNOTHER special property to an IFCWALLTYPE.

I should be able to do this in order to control the information present in the model, customize it, etc. This is the idea.

**Comment by martin1cerny** [comment]
Sure, you can use xBIM for all of this very easily. First from previous code examples shows how to get/modify existing properties/property sets. You can do something like this to add new properties and property sets:

```c#
var wall = model.Instances.OfType<IfcWall>().FirstOrDefault();
var prop = model.Instances.New<IfcPropertySingleValue>(p =>
{
    p.Name = "NewProperty";
    p.NominalValue = new IfcLabel("Sample property value");
});
var pSet = model.Instances.New<IfcPropertySet>(ps =>
{
    ps.Name = "NewPropertySet"; //this SHOULDN'T start with 'Pset_'
    ps.HasProperties.Add_Reversible(prop);
});
wall.AddPropertySet(pSet);
```

**Comment by IFChaos** [comment]
Hi Martin

Thanks, this method is what i need to generate new properties and i also can obtain the predefined PSETS, this is what i need.
